### ISSUE TITLE
ansible-ios-module

### ISSUE THREAD

**Issue by bfernando1** [CiscoDevNet/learning-labs-issues#261]
In [ansible-ios-module][lab] the Playbook uses port 8181 to connect to the IOS device. This port isn't open from the dev box or my local machine. 

```
nc -zv 10.10.20.48 8181
nc: connectx to 10.10.20.48 port 8181 (tcp) failed: Connection refused
```

After updating `group_vars/iosxe.yaml` to port 22, the playbook then times out. 

Here's what I used to test: 

`ansible-playbook ansible-02-ios-modules/02-ios_command_show_ntp.yaml -i hosts -e "hosts=iosxe"`

Here's how I modified group_vars 
```yaml
ansible_connection: network_cli
ansible_become: yes
ansible_become_method: enable
ansible_network_os: ios
ansible_user: 'developer'
ansible_ssh_pass: 'C1sco12345'
ansible_port: 22
```

 
[lab]: https://developer.cisco.com/learning/modules/intro-ansible-iosxe/ansible-ios-modules/step/2
